//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary XWC1.0 
	 /// </summary>
	[SupportByLibrary("XWC1.0")]
	public enum PivotCommandId
	{
		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAbout = 1007,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandDelete = 1011,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFilterBySel = 12001,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandChooser = 1010,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandProperties = 1005,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandInsertField = 12004,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoSum = 12005,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoCount = 12006,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoMin = 12007,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoMax = 12008,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandDropzones = 12009,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandRemove = 12010,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandNextHorz = 12012,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandNextVert = 12013,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLeftEdge = 12014,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandRightEdge = 12015,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandTopLeftEdge = 12016,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandBottomRightEdge = 12017,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandNextHorzCell = 12018,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPrevHorzCell = 12019,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLastLeft = 12020,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLastRight = 12021,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLastUp = 12022,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLastDown = 12023,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandEnterDetails = 12024,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExitDetails = 12025,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandLeft = 12026,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandRight = 12027,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandUp = 12028,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandDown = 12029,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPageUp = 12030,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPageDown = 12031,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPageLeft = 12032,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPageRight = 12033,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandGroupByRow = 12034,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandGroupByColumn = 12035,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandUngroup = 12036,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFilter = 12037,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPromote = 12038,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandDemote = 12039,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExpand = 1012,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandCollapse = 1013,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSubtotal = 12042,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExport = 1004,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandToolbar = 12044,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSortAsc = 2000,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSortDesc = 2031,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandClearCustomOrdering = 12154,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandHelp = 1006,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandRefresh = 1014,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoFilter = 1017,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandCopy = 1002,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExpandIndicator = 12051,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSelectField = 12052,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSelectRow = 12053,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandSelectAll = 12054,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatGeneral = 12055,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatCurrency = 12056,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatPercent = 12057,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatExponent = 12058,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatDate = 12059,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatTime = 12060,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatComma = 12061,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatBold = 12062,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatItalic = 12063,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatUnderline = 12064,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatUnderline2 = 12146,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFilterByMenu = 12065,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandContextMenu = 12066,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPrevHorz = 12067,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPrevVert = 12068,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandNextVertCell = 12069,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPrevVertCell = 12070,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendLeft = 12072,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendRight = 12073,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendUp = 12074,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendDown = 12075,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendPageLeft = 12076,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendPageRight = 12077,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendPageUp = 12078,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendPageDown = 12079,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandHyperlink = 12082,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandOpenHyperlinkInPlace = 12083,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandOpenHyperlinkInWindow = 12084,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandMoveMemUp = 12085,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandMoveMemDown = 12086,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandMoveMemLeft = 12087,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandMoveMemRight = 12088,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoAverage = 12089,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoStdDev = 12090,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoVar = 12091,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoStdDevP = 12092,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoVarP = 12093,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowDetails = 12095,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandHideDetails = 12096,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandTogglePropertiesInReport = 12097,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandTogglePropertiesInScreenTip = 12098,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandStartEdit = 12099,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandEndEdit = 12100,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandDeleteRow = 12101,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandCreateCalculatedTotal = 12102,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandPaste = 1003,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendTopLeftEdge = 12107,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandExtendBottomRightEdge = 12108,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandTogglePropertyInReport = 12900,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandTogglePropertyInScreenTip = 12950,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandAutoCalc = 1016,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandCalculated = 12110,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop1 = 1100,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop2 = 1101,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop5 = 1102,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop10 = 1103,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop25 = 1104,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop1Percent = 1105,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop2Percent = 1106,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop5Percent = 1107,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop10Percent = 1108,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTop25Percent = 1109,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom1 = 1110,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom2 = 1111,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom5 = 1112,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom10 = 1113,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom25 = 1114,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom1Percent = 1115,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom2Percent = 1116,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom5Percent = 1117,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom10Percent = 1118,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottom25Percent = 1119,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowOther = 1120,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAll = 1121,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowTopNMenu = 1123,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowBottomNMenu = 1124,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandConditionalFilter = 1125,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAs = 12134,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsNormal = 12135,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsPercentOfRowTotal = 12136,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsPercentOfColumnTotal = 12137,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsPercentOfRowParent = 12138,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsPercentOfColumnParent = 12139,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAsPercentOfGrandTotal = 12140,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatAlignLeft = 12141,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatAlignCenter = 12142,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatAlignRight = 12143,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatAlignAutomatic = 12158,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatName = 12144,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatSize = 12145,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatForeColor = 12147,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandFormatBackColor = 12148,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAllPropertiesInReport = 12149,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandHideAllPropertiesInReport = 12150,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandShowAllPropertiesInScreenTip = 12151,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandHideAllPropertiesInScreenTip = 12152,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandProfile = 12153,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandGroupMembers = 12155,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandUngroupMembers = 12156,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		plCommandCut = 12157
	}
}