//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 9,10,11,12,14,
	 /// </summary>
	[SupportByLibrary("PowerPoint", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PpAdvanceMode
	{
		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		ppAdvanceModeMixed = -2,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		ppAdvanceOnClick = 1,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		ppAdvanceOnTime = 2
	}
}