//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
	 /// </summary>
	[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
	public enum PpChartUnitEffect
	{
		 /// <summary>
		 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
		ppAnimateChartMixed = -2,

		 /// <summary>
		 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
		ppAnimateBySeries = 1,

		 /// <summary>
		 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
		ppAnimateByCategory = 2,

		 /// <summary>
		 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
		ppAnimateBySeriesElements = 3,

		 /// <summary>
		 /// SupportByLibrary PP09 PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP09","PP10","PP11","PP12","PP14")]
		ppAnimateByCategoryElements = 4,

		 /// <summary>
		 /// SupportByLibrary PP10 PP11 PP12 PP14 
		 /// </summary>
		[SupportByLibrary("PP10","PP11","PP12","PP14")]
		ppAnimateChartAllAtOnce = 5
	}
}