//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary PP14 
	 /// </summary>
	[SupportByLibrary("PP14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PpMediaTaskStatus
	{
		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		ppMediaTaskStatusNone = 0,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		ppMediaTaskStatusInProgress = 1,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		ppMediaTaskStatusQueued = 2,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		ppMediaTaskStatusDone = 3,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		ppMediaTaskStatusFailed = 4
	}
}