//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 14,
	 /// </summary>
	[SupportByLibrary("PowerPoint", 14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PpPlayerState
	{
		 /// <summary>
		 /// SupportByLibrary 14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 14)]
		ppPlaying = 0,

		 /// <summary>
		 /// SupportByLibrary 14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 14)]
		ppPaused = 1,

		 /// <summary>
		 /// SupportByLibrary 14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 14)]
		ppStopped = 2,

		 /// <summary>
		 /// SupportByLibrary 14,
		 /// </summary>
		[SupportByLibrary("PowerPoint", 14)]
		ppNotReady = 3
	}
}