//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary PP14 
	 /// </summary>
	[SupportByLibrary("PP14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlErrorBarInclude
	{
		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		xlErrorBarIncludeBoth = 1,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		xlErrorBarIncludeMinusValues = 3,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		xlErrorBarIncludeNone = -4142,

		 /// <summary>
		 /// SupportByLibrary PP14 
		 /// </summary>
		[SupportByLibrary("PP14")]
		xlErrorBarIncludePlusValues = 2
	}
}