//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OfficeApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("Office", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum MsoArrowheadStyle
	{
		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>-2</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadStyleMixed = -2,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadNone = 1,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadTriangle = 2,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>3</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadOpen = 3,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadStealth = 4,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadDiamond = 5,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoArrowheadOval = 6
	}
}