//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.OfficeApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary OF09 OF10 OF11 OF12 OF14 
	 /// </summary>
	[SupportByLibrary("OF09","OF10","OF11","OF12","OF14")]
	public enum MsoGradientColorType
	{
		 /// <summary>
		 /// SupportByLibrary OF09 OF10 OF11 OF12 OF14 
		 /// </summary>
		[SupportByLibrary("OF09","OF10","OF11","OF12","OF14")]
		msoGradientColorMixed = -2,

		 /// <summary>
		 /// SupportByLibrary OF09 OF10 OF11 OF12 OF14 
		 /// </summary>
		[SupportByLibrary("OF09","OF10","OF11","OF12","OF14")]
		msoGradientOneColor = 1,

		 /// <summary>
		 /// SupportByLibrary OF09 OF10 OF11 OF12 OF14 
		 /// </summary>
		[SupportByLibrary("OF09","OF10","OF11","OF12","OF14")]
		msoGradientTwoColors = 2,

		 /// <summary>
		 /// SupportByLibrary OF09 OF10 OF11 OF12 OF14 
		 /// </summary>
		[SupportByLibrary("OF09","OF10","OF11","OF12","OF14")]
		msoGradientPresetColors = 3,

		 /// <summary>
		 /// SupportByLibrary OF12 OF14 
		 /// </summary>
		[SupportByLibrary("OF12","OF14")]
		msoGradientMultiColor = 4
	}
}