//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.MSHTMLApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary MSHTML 4, 
	 /// </summary>
	[SupportByLibrary("MSHTML", 4)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum _DomConstructor
	{
		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorObject = 0,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorAttr = 1,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorBehaviorUrnsCollection = 2,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>3</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorBookmarkCollection = 3,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCompatibleInfo = 4,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCompatibleInfoCollection = 5,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorControlRangeCollection = 6,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>7</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSCurrentStyleDeclaration = 7,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>8</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSRuleList = 8,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>9</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSRuleStyleDeclaration = 9,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>10</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSStyleDeclaration = 10,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>11</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSStyleRule = 11,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>12</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorCSSStyleSheet = 12,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>13</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorDataTransfer = 13,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>14</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorDOMImplementation = 14,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>15</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorElement = 15,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>16</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorEvent = 16,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>17</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHistory = 17,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>18</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTCElementBehaviorDefaults = 18,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>19</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLAnchorElement = 19,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>20</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLAreaElement = 20,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>21</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLAreasCollection = 21,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>22</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBaseElement = 22,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>23</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBaseFontElement = 23,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>24</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBGSoundElement = 24,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>25</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBlockElement = 25,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>26</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBodyElement = 26,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>27</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLBRElement = 27,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>28</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLButtonElement = 28,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>29</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLCollection = 29,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>30</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLCommentElement = 30,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>31</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLDDElement = 31,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>32</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLDivElement = 32,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>33</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLDocument = 33,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>34</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLDListElement = 34,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>35</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLDTElement = 35,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>36</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLEmbedElement = 36,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>37</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLFieldSetElement = 37,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>38</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLFontElement = 38,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>39</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLFormElement = 39,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>40</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLFrameElement = 40,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>41</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLFrameSetElement = 41,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>42</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLGenericElement = 42,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>43</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLHeadElement = 43,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>44</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLHeadingElement = 44,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>45</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLHRElement = 45,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>46</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLHtmlElement = 46,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>47</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLIFrameElement = 47,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>48</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLImageElement = 48,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>49</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLInputElement = 49,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>50</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLIsIndexElement = 50,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>51</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLLabelElement = 51,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>52</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLLegendElement = 52,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>53</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLLIElement = 53,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>54</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLLinkElement = 54,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>55</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLMapElement = 55,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>56</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLMarqueeElement = 56,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>57</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLMetaElement = 57,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>58</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLModelessDialog = 58,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>59</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLNamespaceInfo = 59,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>60</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLNamespaceInfoCollection = 60,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>61</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLNextIdElement = 61,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>62</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLNoShowElement = 62,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>63</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLObjectElement = 63,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>64</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLOListElement = 64,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>65</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLOptionElement = 65,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>66</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLParagraphElement = 66,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>67</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLParamElement = 67,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>68</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLPhraseElement = 68,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>69</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLPluginsCollection = 69,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>70</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLPopup = 70,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>71</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLScriptElement = 71,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>72</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLSelectElement = 72,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>73</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLSpanElement = 73,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>74</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLStyleElement = 74,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>75</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableCaptionElement = 75,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>76</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableCellElement = 76,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>77</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableColElement = 77,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>78</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableElement = 78,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>79</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableRowElement = 79,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>80</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTableSectionElement = 80,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>81</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTextAreaElement = 81,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>82</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTextElement = 82,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>83</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLTitleElement = 83,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>84</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLUListElement = 84,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>85</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorHTMLUnknownElement = 85,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>86</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorImage = 86,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>87</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorLocation = 87,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>88</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorNamedNodeMap = 88,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>89</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorNavigator = 89,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>90</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorNodeList = 90,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>91</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorOption = 91,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>92</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorScreen = 92,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>93</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorSelection = 93,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>94</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorStaticNodeList = 94,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>95</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorStorage = 95,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>96</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorStyleSheetList = 96,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>97</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorStyleSheetPage = 97,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>98</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorStyleSheetPageList = 98,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>99</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorText = 99,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>100</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorTextRange = 100,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>101</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorTextRangeCollection = 101,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>102</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorTextRectangle = 102,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>103</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorTextRectangleList = 103,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>104</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorWindow = 104,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>105</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorXDomainRequest = 105,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>106</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorXMLHttpRequest = 106,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>107</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructorMax = 107,

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		 /// <remarks>2147483647</remarks>
		 [SupportByLibrary("MSHTML", 4)]
		 DomConstructor_Max = 2147483647
	}
}