//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary XL09 XL10 XL11 XL12 XL14 
	 /// </summary>
	[SupportByLibrary("XL09","XL10","XL11","XL12","XL14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlPictureAppearance
	{
		 /// <summary>
		 /// SupportByLibrary XL09 XL10 XL11 XL12 XL14 
		 /// </summary>
		[SupportByLibrary("XL09","XL10","XL11","XL12","XL14")]
		xlPrinter = 2,

		 /// <summary>
		 /// SupportByLibrary XL09 XL10 XL11 XL12 XL14 
		 /// </summary>
		[SupportByLibrary("XL09","XL10","XL11","XL12","XL14")]
		xlScreen = 1
	}
}