//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 10,11,12,14,
	 /// </summary>
	[SupportByLibrary("Excel", 10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlPivotTableMissingItems
	{
		 /// <summary>
		 /// SupportByLibrary 10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlMissingItemsDefault = -1,

		 /// <summary>
		 /// SupportByLibrary 10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlMissingItemsNone = 0,

		 /// <summary>
		 /// SupportByLibrary 10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlMissingItemsMax = 32500,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 12,14)]
		xlMissingItemsMax2 = 1048576
	}
}