//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Excel 10, 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("Excel", 10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlSmartTagDisplayMode
	{
		 /// <summary>
		 /// SupportByLibrary Excel 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlIndicatorAndButton = 0,

		 /// <summary>
		 /// SupportByLibrary Excel 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlDisplayNone = 1,

		 /// <summary>
		 /// SupportByLibrary Excel 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Excel", 10,11,12,14)]
		xlButtonOnly = 2
	}
}