//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 12,14,
	 /// </summary>
	[SupportByLibrary("Excel", 12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlSortOn
	{
		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 12,14)]
		xlSortOnValues = 0,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 12,14)]
		xlSortOnCellColor = 1,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 12,14)]
		xlSortOnFontColor = 2,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Excel", 12,14)]
		xlSortOnIcon = 3
	}
}