//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary XL14 
	 /// </summary>
	[SupportByLibrary("XL14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlSparkScale
	{
		 /// <summary>
		 /// SupportByLibrary XL14 
		 /// </summary>
		[SupportByLibrary("XL14")]
		xlSparkScaleGroup = 1,

		 /// <summary>
		 /// SupportByLibrary XL14 
		 /// </summary>
		[SupportByLibrary("XL14")]
		xlSparkScaleSingle = 2,

		 /// <summary>
		 /// SupportByLibrary XL14 
		 /// </summary>
		[SupportByLibrary("XL14")]
		xlSparkScaleCustom = 3
	}
}