//Generated by LateBindingApi.CodeGenerator
using System;
using NetRuntimeSystem = System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.ComponentModel;
using System.Reflection;
using LateBindingApi.Core;
namespace LateBindingApi.MSHTMLApi
{
	///<summary>
	/// DispatchInterface DispHTMLDOMImplementation SupportByLibraryAttribute MSHTML, 4
	///</summary>
	[SupportByLibraryAttribute("MSHTML", 4)]
	[EntityTypeAttribute(EntityType.IsDispatchInterface)]
	public class DispHTMLDOMImplementation : COMObject
	{
		#pragma warning disable
		#region Type Information

        private static Type _type;

		[EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
        public static Type LateBindingApiWrapperType
        {
            get
            {
                if (null == _type)
                    _type = typeof(DispHTMLDOMImplementation);
                    
                return _type;
            }
        }
        
        #endregion
        
		#region Construction

        /// <param name="parentObject">object there has created the proxy</param>
        /// <param name="comProxy">inner wrapped COM proxy</param>
        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
		public DispHTMLDOMImplementation(COMObject parentObject, object comProxy) : base(parentObject, comProxy)
		{
		}
		
		/// <param name="parentObject">object there has created the proxy</param>
        /// <param name="comProxy">inner wrapped COM proxy</param>
        /// <param name="comProxyType">Type of inner wrapped COM proxy"</param>
        [EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
		public DispHTMLDOMImplementation(COMObject parentObject, object comProxy, NetRuntimeSystem.Type comProxyType) : base(parentObject, comProxy, comProxyType)
		{
		}
		
		/// <param name="replacedObject">object to replaced. replacedObject are not usable after this action</param>
		[EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
		public DispHTMLDOMImplementation(COMObject replacedObject) : base(replacedObject)
		{
		}
		
		[EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
		public DispHTMLDOMImplementation() : base()
		{
		}
		
		/// <param name="progId">registered ProgID</param>
		[EditorBrowsable(EditorBrowsableState.Never), Browsable(false)]
		public DispHTMLDOMImplementation(string progId) : base(progId)
		{
		}
		
		#endregion
		
		#region Properties

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// Get
		/// </summary>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public COMObject constructor
		{
			get
			{
				object[] paramsArray = null;
				object returnItem = Invoker.PropertyGet(this, "constructor", paramsArray);
				COMObject newObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this,returnItem);
				return newObject;
			}
		}

		#endregion

		#region Methods

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrfeature">string bstrfeature</param>
		/// <param name="version">optional object version</param>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public bool hasFeature(string bstrfeature, object version)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrfeature, version);
			object returnItem = Invoker.MethodReturn(this, "hasFeature", paramsArray);
			return (bool)returnItem;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrfeature">string bstrfeature</param>
		[CustomMethodAttribute]
		[SupportByLibraryAttribute("MSHTML", 4)]
		public bool hasFeature(string bstrfeature)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrfeature);
			object returnItem = Invoker.MethodReturn(this, "hasFeature", paramsArray);
			return (bool)returnItem;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrQualifiedName">string bstrQualifiedName</param>
		/// <param name="pvarPublicId">object pvarPublicId</param>
		/// <param name="pvarSystemId">object pvarSystemId</param>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public LateBindingApi.MSHTMLApi.IDOMDocumentType createDocumentType(string bstrQualifiedName, object pvarPublicId, object pvarSystemId)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrQualifiedName, pvarPublicId, pvarSystemId);
			object returnItem = Invoker.MethodReturn(this, "createDocumentType", paramsArray);
			LateBindingApi.MSHTMLApi.IDOMDocumentType newObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this,returnItem) as LateBindingApi.MSHTMLApi.IDOMDocumentType;
			return newObject;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="pvarNS">object pvarNS</param>
		/// <param name="pvarTagName">object pvarTagName</param>
		/// <param name="pDocumentType">LateBindingApi.MSHTMLApi.IDOMDocumentType pDocumentType</param>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public LateBindingApi.MSHTMLApi.IHTMLDocument7 createDocument(object pvarNS, object pvarTagName, LateBindingApi.MSHTMLApi.IDOMDocumentType pDocumentType)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(pvarNS, pvarTagName, pDocumentType);
			object returnItem = Invoker.MethodReturn(this, "createDocument", paramsArray);
			LateBindingApi.MSHTMLApi.IHTMLDocument7 newObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this,returnItem) as LateBindingApi.MSHTMLApi.IHTMLDocument7;
			return newObject;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrTitle">string bstrTitle</param>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public LateBindingApi.MSHTMLApi.IHTMLDocument7 createHTMLDocument(string bstrTitle)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrTitle);
			object returnItem = Invoker.MethodReturn(this, "createHTMLDocument", paramsArray);
			LateBindingApi.MSHTMLApi.IHTMLDocument7 newObject = LateBindingApi.Core.Factory.CreateObjectFromComProxy(this,returnItem) as LateBindingApi.MSHTMLApi.IHTMLDocument7;
			return newObject;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrfeature">string bstrfeature</param>
		/// <param name="version">optional object version</param>
		[SupportByLibraryAttribute("MSHTML", 4)]
		public bool ie9_hasFeature(string bstrfeature, object version)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrfeature, version);
			object returnItem = Invoker.MethodReturn(this, "ie9_hasFeature", paramsArray);
			return (bool)returnItem;
		}

		/// <summary>
		/// SupportByLibrary MSHTML 4
		/// </summary>
		/// <param name="bstrfeature">string bstrfeature</param>
		[CustomMethodAttribute]
		[SupportByLibraryAttribute("MSHTML", 4)]
		public bool ie9_hasFeature(string bstrfeature)
		{
			object[] paramsArray = Invoker.ValidateParamsArray(bstrfeature);
			object returnItem = Invoker.MethodReturn(this, "ie9_hasFeature", paramsArray);
			return (bool)returnItem;
		}

		#endregion
		#pragma warning restore
	}
}