//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary OWC10 1
	 /// </summary>
	[SupportByLibraryAttribute("OWC10", 1)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum TipTypeEnum
	{
		 /// <summary>
		 /// SupportByLibrary OWC10 1
		 /// </summary>
		 /// <remarks>-1</remarks>
		 [SupportByLibraryAttribute("OWC10", 1)]
		 eTipTypeNone = -1,

		 /// <summary>
		 /// SupportByLibrary OWC10 1
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibraryAttribute("OWC10", 1)]
		 eTipTypeText = 0,

		 /// <summary>
		 /// SupportByLibrary OWC10 1
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibraryAttribute("OWC10", 1)]
		 eTipTypeHTML = 1,

		 /// <summary>
		 /// SupportByLibrary OWC10 1
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibraryAttribute("OWC10", 1)]
		 eTipTypeAuto = 2
	}
}