//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ExcelApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Excel 9, 10, 11, 12, 14
	 /// </summary>
	[SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum xlQueryType
	{
		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlODBCQuery = 1,

		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlDAORecordSet = 2,

		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlWebQuery = 4,

		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlOLEDBQuery = 5,

		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlTextImport = 6,

		 /// <summary>
		 /// SupportByLibrary Excel 9, 10, 11, 12, 14
		 /// </summary>
		 /// <remarks>7</remarks>
		 [SupportByLibraryAttribute("Excel", 9,10,11,12,14)]
		 xlADORecordset = 7
	}
}