//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OfficeApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("Office", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum MsoButtonStyleHidden
	{
		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoButtonWrapText = 4,

		 /// <summary>
		 /// SupportByLibrary Office 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>8</remarks>
		 [SupportByLibrary("Office", 9,10,11,12,14)]
		 msoButtonTextBelow = 8
	}
}