//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ADODBApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary ADODB 2.1, 2.5
	 /// </summary>
	[SupportByLibraryAttribute("ADODB", 2.1,2.5)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum ConnectOptionEnum
	{
		 /// <summary>
		 /// SupportByLibrary ADODB 2.1, 2.5
		 /// </summary>
		 /// <remarks>-1</remarks>
		 [SupportByLibraryAttribute("ADODB", 2.1,2.5)]
		 adConnectUnspecified = -1,

		 /// <summary>
		 /// SupportByLibrary ADODB 2.1, 2.5
		 /// </summary>
		 /// <remarks>16</remarks>
		 [SupportByLibraryAttribute("ADODB", 2.1,2.5)]
		 adAsyncConnect = 16
	}
}