//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OutlookApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary OL12 OL14 
	 /// </summary>
	[SupportByLibrary("OL12","OL14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum OlAddressListType
	{
		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olExchangeGlobalAddressList = 0,

		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olExchangeContainer = 1,

		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olOutlookAddressList = 2,

		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olOutlookLdapAddressList = 3,

		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olCustomAddressList = 4
	}
}