//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OutlookApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary OL12 OL14 
	 /// </summary>
	[SupportByLibrary("OL12","OL14")]
	public enum OlCalendarMailFormat
	{
		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olCalendarMailFormatDailySchedule = 0,

		 /// <summary>
		 /// SupportByLibrary OL12 OL14 
		 /// </summary>
		[SupportByLibrary("OL12","OL14")]
		olCalendarMailFormatEventList = 1
	}
}