//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OutlookApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 12,14,
	 /// </summary>
	[SupportByLibrary("Outlook", 12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum OlFormatKeywords
	{
		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Outlook", 12,14)]
		olFormatKeywordsText = 1
	}
}