//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OutlookApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Outlook 10, 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("Outlook", 10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum OlViewSaveOption
	{
		 /// <summary>
		 /// SupportByLibrary Outlook 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Outlook", 10,11,12,14)]
		olViewSaveOptionThisFolderEveryone = 0,

		 /// <summary>
		 /// SupportByLibrary Outlook 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Outlook", 10,11,12,14)]
		olViewSaveOptionThisFolderOnlyMe = 1,

		 /// <summary>
		 /// SupportByLibrary Outlook 10, 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Outlook", 10,11,12,14)]
		olViewSaveOptionAllFoldersOfType = 2
	}
}