//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.PowerPointApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("PowerPoint", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PpNumberedBulletStyle
	{
		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>-2</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletStyleMixed = -2,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaLCPeriod = 0,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaUCPeriod = 1,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicParenRight = 2,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>3</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicPeriod = 3,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanLCParenBoth = 4,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanLCParenRight = 5,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanLCPeriod = 6,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>7</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanUCPeriod = 7,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>8</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaLCParenBoth = 8,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>9</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaLCParenRight = 9,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>10</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaUCParenBoth = 10,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>11</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletAlphaUCParenRight = 11,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>12</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicParenBoth = 12,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>13</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicPlain = 13,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>14</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanUCParenBoth = 14,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>15</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletRomanUCParenRight = 15,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>16</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletSimpChinPlain = 16,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>17</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletSimpChinPeriod = 17,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>18</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletCircleNumDBPlain = 18,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>19</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletCircleNumWDWhitePlain = 19,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>20</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletCircleNumWDBlackPlain = 20,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>21</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletTradChinPlain = 21,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>22</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletTradChinPeriod = 22,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>23</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicAlphaDash = 23,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>24</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicAbjadDash = 24,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>25</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletHebrewAlphaDash = 25,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>26</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletKanjiKoreanPlain = 26,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>27</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletKanjiKoreanPeriod = 27,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>28</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicDBPlain = 28,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 9, 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>29</remarks>
		 [SupportByLibrary("PowerPoint", 9,10,11,12,14)]
		 ppBulletArabicDBPeriod = 29,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>30</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiAlphaPeriod = 30,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>31</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiAlphaParenRight = 31,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>32</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiAlphaParenBoth = 32,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>33</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiNumPeriod = 33,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>34</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiNumParenRight = 34,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>35</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletThaiNumParenBoth = 35,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>36</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletHindiAlphaPeriod = 36,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>37</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletHindiNumPeriod = 37,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>38</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletKanjiSimpChinDBPeriod = 38,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>39</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletHindiNumParenRight = 39,

		 /// <summary>
		 /// SupportByLibrary PowerPoint 10, 11, 12, 14, 
		 /// </summary>
		 /// <remarks>40</remarks>
		 [SupportByLibrary("PowerPoint", 10,11,12,14)]
		 ppBulletHindiAlpha1Period = 40
	}
}