//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary OWC10 1, 
	 /// </summary>
	[SupportByLibrary("OWC10", 1)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum ChartTitlePositionEnum
	{
		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		chTitlePositionAutomatic = 0,

		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		chTitlePositionTop = 1,

		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		chTitlePositionBottom = 2,

		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		chTitlePositionLeft = 3,

		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		chTitlePositionRight = 4
	}
}