//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary XWC1.0 
	 /// </summary>
	[SupportByLibrary("XWC1.0")]
	public enum NavButtonEnum
	{
		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnMoveFirst = 0,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnMovePrev = 1,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnMoveNext = 2,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnMoveLast = 3,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnNew = 4,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnDelete = 5,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnSave = 6,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnUndo = 7,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnSortAscending = 8,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnSortDescending = 9,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnApplyFilter = 10,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnToggleFilter = 11,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		navbtnHelp = 12
	}
}