//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary XWC1.0 
	 /// </summary>
	[SupportByLibrary("XWC1.0")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum SynchronizationStatus
	{
		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		dscSynchronizing = 0,

		 /// <summary>
		 /// SupportByLibrary XWC1.0 
		 /// </summary>
		[SupportByLibrary("XWC1.0")]
		dscSynchronizationDone = 1
	}
}