//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.OWC10Api.Enums
{
	 /// <summary>
	 /// SupportByLibrary OWC10 1, 
	 /// </summary>
	[SupportByLibrary("OWC10", 1)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum XlLookAt
	{
		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		xlPart = 2,

		 /// <summary>
		 /// SupportByLibrary OWC10 1, 
		 /// </summary>
		[SupportByLibrary("OWC10", 1)]
		xlWhole = 1
	}
}