<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NetOffice.CodeGen.Data</AssemblyName>
    <RootNamespace>NetOffice.CodeGen.Data</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
