//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.MSProjectApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary MSProject 12, 14
	 /// </summary>
	[SupportByLibraryAttribute("MSProject", 12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PjExceptionItem
	{
		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>3</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemSunday = 3,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemMonday = 4,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemTuesday = 5,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemWednesday = 6,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>7</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemThursday = 7,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>8</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemFriday = 8,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14
		 /// </summary>
		 /// <remarks>9</remarks>
		 [SupportByLibraryAttribute("MSProject", 12,14)]
		 pjItemSaturday = 9
	}
}