//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.MSProjectApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary MSProject 12, 14, 
	 /// </summary>
	[SupportByLibrary("MSProject", 12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PjPaperSize
	{
		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>16</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaper10x14 = 16,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>17</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaper11x17 = 17,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>8</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperA3 = 8,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>9</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperA4 = 9,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>10</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperA4Small = 10,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>11</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperA5 = 11,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>12</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperB4 = 12,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>13</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperB5 = 13,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>24</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperCsheet = 24,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>25</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperDsheet = 25,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>20</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelop10 = 20,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>21</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelope11 = 21,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>22</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelope12 = 22,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>23</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelope14 = 23,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>19</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelope9 = 19,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>33</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeB4 = 33,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>34</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeB5 = 34,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>35</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopB6 = 35,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>29</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeC3 = 29,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>30</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeC4 = 30,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>28</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeC5 = 28,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>31</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeC6 = 31,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>32</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeC65 = 32,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>27</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeDL = 27,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>36</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeItaly = 36,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>37</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopeMonarch = 37,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>38</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEnvelopePersonal = 38,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>26</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperEsheet = 26,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>7</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperExecutive = 7,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>41</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperFanfoldLegalGerman = 41,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>40</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperFanfoldStdGerman = 40,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>39</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperFanfoldUS = 39,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>14</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperFolio = 14,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>4</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperLedger = 4,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>5</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperLegal = 5,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperLetter = 1,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperLetterSmall = 2,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>18</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperNote = 18,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>15</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperQuarto = 15,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>6</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperStatement = 6,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>3</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperTabloid = 3,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>255</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperUser = 255,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjPaperDefault = 0
	}
}