//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.MSProjectApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary MSProject 12, 14, 
	 /// </summary>
	[SupportByLibrary("MSProject", 12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum PjPhoneticType
	{
		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjKatakanaHalf = 0,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjKatakana = 1,

		 /// <summary>
		 /// SupportByLibrary MSProject 12, 14, 
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibrary("MSProject", 12,14)]
		 pjHiragana = 2
	}
}