//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.ADODBApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary ADO2.5 
	 /// </summary>
	[SupportByLibrary("ADO2.5")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum ADCPROP_UPDATERESYNC_ENUM
	{
		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncNone = 0,

		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncAutoIncrement = 1,

		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncConflicts = 2,

		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncUpdates = 4,

		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncInserts = 8,

		 /// <summary>
		 /// SupportByLibrary ADO2.5 
		 /// </summary>
		[SupportByLibrary("ADO2.5")]
		adResyncAll = 15
	}
}