//Generated by LateBindingApi.CodeGenerator
using System;
using System.Runtime.InteropServices;
using LateBindingApi.Core;
namespace LateBindingApi.MSHTMLApi
{
	 /// <summary>
	 /// SupportByLibrary MSHTML 4, 
	 /// </summary>
	[SupportByLibrary("MSHTML", 4)]
	[StructLayout(LayoutKind.Sequential, Pack=4), Guid("00000000-0000-0000-0000-000000000000")]
	[EntityTypeAttribute(EntityType.IsStruct)]
	public struct _FLAGGED_BYTE_BLOB
	{
		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		[SupportByLibrary("MSHTML", 4)]
		public Int32 fFlags;

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		[SupportByLibrary("MSHTML", 4)]
		public Int32 clSize;

		 /// <summary>
		 /// SupportByLibrary MSHTML 4, 
		 /// </summary>
		[SupportByLibrary("MSHTML", 4)]
		public byte abData;
	}
}