//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.AccessApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Access 14
	 /// </summary>
	[SupportByLibraryAttribute("Access", 14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum AcWebBrowserScrollBars
	{
		 /// <summary>
		 /// SupportByLibrary Access 14
		 /// </summary>
		 /// <remarks>0</remarks>
		 [SupportByLibraryAttribute("Access", 14)]
		 acScrollAuto = 0,

		 /// <summary>
		 /// SupportByLibrary Access 14
		 /// </summary>
		 /// <remarks>1</remarks>
		 [SupportByLibraryAttribute("Access", 14)]
		 acScrollYes = 1,

		 /// <summary>
		 /// SupportByLibrary Access 14
		 /// </summary>
		 /// <remarks>2</remarks>
		 [SupportByLibraryAttribute("Access", 14)]
		 acScrollNo = 2
	}
}