name: labels

permissions:
  issues: write

on:
  push:
    branches: [ main ]
    paths:
      - '.github/labels.json'
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitlabels/gitlabels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
