//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 9,10,11,12,14,
	 /// </summary>
	[SupportByLibrary("Word", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum WdDictionaryType
	{
		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSpelling = 0,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdGrammar = 1,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdThesaurus = 2,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdHyphenation = 3,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSpellingComplete = 4,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSpellingCustom = 5,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSpellingLegal = 6,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSpellingMedical = 7,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdHangulHanjaConversion = 8,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdHangulHanjaConversionCustom = 9
	}
}