//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary WD09 WD10 WD11 WD12 WD14 
	 /// </summary>
	[SupportByLibrary("WD09","WD10","WD11","WD12","WD14")]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum WdDropPosition
	{
		 /// <summary>
		 /// SupportByLibrary WD09 WD10 WD11 WD12 WD14 
		 /// </summary>
		[SupportByLibrary("WD09","WD10","WD11","WD12","WD14")]
		wdDropNone = 0,

		 /// <summary>
		 /// SupportByLibrary WD09 WD10 WD11 WD12 WD14 
		 /// </summary>
		[SupportByLibrary("WD09","WD10","WD11","WD12","WD14")]
		wdDropNormal = 1,

		 /// <summary>
		 /// SupportByLibrary WD09 WD10 WD11 WD12 WD14 
		 /// </summary>
		[SupportByLibrary("WD09","WD10","WD11","WD12","WD14")]
		wdDropMargin = 2
	}
}