//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 9,10,11,12,14,
	 /// </summary>
	[SupportByLibrary("Word", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum WdSaveOptions
	{
		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdDoNotSaveChanges = 0,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdSaveChanges = -1,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdPromptToSaveChanges = -2
	}
}