//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary Word 11, 12, 14, 
	 /// </summary>
	[SupportByLibrary("Word", 11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum WdSmartTagControlType
	{
		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlSmartTag = 1,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlLink = 2,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlHelp = 3,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlHelpURL = 4,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlSeparator = 5,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlButton = 6,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlLabel = 7,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlImage = 8,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlCheckbox = 9,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlTextbox = 10,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlListbox = 11,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlCombo = 12,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlActiveX = 13,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlDocumentFragment = 14,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlDocumentFragmentURL = 15,

		 /// <summary>
		 /// SupportByLibrary Word 11, 12, 14, 
		 /// </summary>
		[SupportByLibrary("Word", 11,12,14)]
		wdControlRadioGroup = 16
	}
}