//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace NetOffice.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary 9,10,11,12,14,
	 /// </summary>
	[SupportByLibrary("Word", 9,10,11,12,14)]
	[EntityTypeAttribute(EntityType.IsEnum)]
	public enum WdWrapType
	{
		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdWrapSquare = 0,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdWrapTight = 1,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdWrapThrough = 2,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdWrapNone = 3,

		 /// <summary>
		 /// SupportByLibrary 9,10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 9,10,11,12,14)]
		wdWrapTopBottom = 4,

		 /// <summary>
		 /// SupportByLibrary 10,11,12,14,
		 /// </summary>
		[SupportByLibrary("Word", 10,11,12,14)]
		wdWrapInline = 7,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Word", 12,14)]
		wdWrapBehind = 5,

		 /// <summary>
		 /// SupportByLibrary 12,14,
		 /// </summary>
		[SupportByLibrary("Word", 12,14)]
		wdWrapFront = 3
	}
}