//Generated by LateBindingApi.CodeGenerator
using System;
using LateBindingApi.Core;
namespace LateBindingApi.WordApi.Enums
{
	 /// <summary>
	 /// SupportByLibrary WD14 
	 /// </summary>
	[SupportByLibrary("WD14")]
	public enum XlPattern
	{
		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternAutomatic = -4105,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternChecker = 9,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternCrissCross = 16,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternDown = -4121,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGray16 = 17,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGray25 = -4124,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGray50 = -4125,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGray75 = -4126,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGray8 = 18,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternGrid = 15,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternHorizontal = -4128,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternLightDown = 13,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternLightHorizontal = 11,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternLightUp = 14,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternLightVertical = 12,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternNone = -4142,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternSemiGray75 = 10,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternSolid = 1,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternUp = -4162,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternVertical = -4166,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternLinearGradient = 4000,

		 /// <summary>
		 /// SupportByLibrary WD14 
		 /// </summary>
		[SupportByLibrary("WD14")]
		xlPatternRectangularGradient = 4001
	}
}